# Generated by Django 4.2.2 on 2023-09-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quest_text',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
