# Generated by Django 4.2.2 on 2023-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_quest_text'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-publi_date'], name='polls_quest_publi_d_8955dd_idx'),
        ),
    ]
