# Generated by Django 4.2.2 on 2023-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_polls_quest_publi_d_8955dd_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publi_date',
            field=models.DateTimeField(db_index=True, verbose_name='date published'),
        ),
    ]
