# Generated by Django 4.2.2 on 2023-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_publi_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='polls_quest_publi_d_8955dd_idx',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-quest_text'], name='polls_quest_quest_t_477917_idx'),
        ),
    ]
